DOMAIN = "bacnet_hub"
DEFAULT_NAME = "BACnet Hub"

CONF_ADDRESS = "address"
CONF_PORT = "port"
CONF_INSTANCE = "instance"
CONF_DEVICE_NAME = "device_name"
CONF_BBMD_IP = "bbmd_ip"
CONF_BBMD_TTL = "bbmd_ttl"
CONF_OBJECTS_YAML = "objects_yaml"
